-- Seed the blog with six published posts so the public /blog page
-- has content on a fresh install. Mirrors `lib/blog/seed.ts`.
-- Apply via Supabase SQL Editor or `supabase db push`.

insert into public.blog_posts (
  id, slug, title, subtitle, cover_image_url, content_html,
  category, tags, status, scheduled_for, reading_time,
  meta_title, meta_description, author_id, author_name,
  published_at, created_at, updated_at
) values
(
  'seed-001',
  'bns-2023-cheat-sheet-for-advocates',
  'BNS 2023 — a working cheat-sheet for the practising advocate',
  'Mapping the new Bharatiya Nyaya Sanhita onto the IPC sections you''ve practised for a decade.',
  '/landing/lawbook.jpg',
  '<p>The BNS replaces the IPC for substantive criminal law. This piece maps the most-used sections in everyday practice — 302/304B, 306, 498A, 376, 392, 420 — onto their BNS equivalents, flags the changes in punishment tiers, and notes the procedural flow-on effects under BNSS.</p><p>We focus on the sections you''ll actually see in your cause-list this fortnight, not the entire 358-section statute.</p>',
  'Practice',
  array['BNS','IPC','Criminal Law','Cheat Sheet'],
  'published',
  null,
  7,
  'BNS 2023 cheat-sheet for advocates | LexRam Blog',
  'A practical mapping of BNS 2023 onto the IPC sections Indian advocates use every week.',
  null,
  'LexRam Editorial',
  '2026-07-08T09:00:00+05:30',
  '2026-07-08T09:00:00+05:30',
  '2026-07-08T09:00:00+05:30'
),
(
  'seed-002',
  'from-manual-research-to-ai-assisted-research',
  'From manual cite-checking to AI-assisted research: a senior counsel''s first 30 days',
  'What changed, what didn''t, and the one workflow rewrite that mattered most.',
  '/landing/research-img.jpg',
  '<p>We followed three senior advocates through their first 30 days with an AI research tool. This is the unvarnished log — what saved time, what was friction, and which parts of the old workflow they ended up keeping.</p><p>The short version: source-linked citations turned out to matter more than model speed.</p>',
  'Technology',
  array['AI Research','Workflow','Advocates'],
  'published',
  null,
  9,
  'AI-assisted legal research — a 30-day field log | LexRam Blog',
  'Senior advocates share what changes — and what doesn''t — when AI enters the research workflow.',
  null,
  'LexRam Editorial',
  '2026-07-03T10:30:00+05:30',
  '2026-07-03T10:30:00+05:30',
  '2026-07-03T10:30:00+05:30'
),
(
  'seed-003',
  'drafting-bail-applications-with-llms',
  'Drafting a bail application with an LLM — the parts you still review',
  'The output looks finished. It is not. Here is your line-by-line review checklist.',
  '/landing/drafting-img.jpg',
  '<p>An LLM drafts a section 437 BNSS bail application in fifteen seconds. You will spend twenty minutes on review. Here is what deserves those twenty minutes — facts the model cannot verify, citations it cannot trace, and reliefs that must match the case diary.</p>',
  'Practice',
  array['Drafting','Bail','LLM','Review'],
  'published',
  null,
  6,
  'AI-drafted bail applications — the review checklist | LexRam Blog',
  'Which parts of an LLM-drafted bail application need an advocate''s eyes before filing.',
  null,
  'LexRam Editorial',
  '2026-06-28T08:00:00+05:30',
  '2026-06-28T08:00:00+05:30',
  '2026-06-28T08:00:00+05:30'
),
(
  'seed-004',
  'data-protection-act-2023-and-chambers',
  'The DPDP Act 2023 and what chambers actually have to do',
  'Six obligations you''ll face; one you''ll almost certainly forget.',
  '/landing/chamber.jpg',
  '<p>The Digital Personal Data Protection Act 2023 turned most chambers into ''Data Fiduciaries'' the moment they process client files. Here are the six obligations that fall on you, what triggers each, and the one that''s consistently overlooked — the Grievance Redressal officer.</p>',
  'Compliance',
  array['DPDP','Compliance','Data Protection','Chambers'],
  'published',
  null,
  8,
  'DPDP Act 2023 obligations on law chambers | LexRam Blog',
  'Six concrete obligations the DPDP Act 2023 places on advocates and law chambers — and the one most firms miss.',
  null,
  'LexRam Editorial',
  '2026-06-22T11:15:00+05:30',
  '2026-06-22T11:15:00+05:30',
  '2026-06-22T11:15:00+05:30'
),
(
  'seed-005',
  'reading-supreme-court-judgments-faster',
  'Reading a Supreme Court judgment faster — without losing the ratio',
  'Five highlighter moves that turn a 40-page judgment into a five-minute understanding.',
  '/landing/courthouse.jpg',
  '<p>Most judgments bury the ratio under facts and obiter. These five moves — which paragraphs you read first, what you skip, what you flag — get you the law without the 40-page grind. Includes an example with Arnesh Kumar (2014) and what makes it a faster read than its length suggests.</p>',
  'Analysis',
  array['Judgment Reading','Supreme Court','Ratio'],
  'published',
  null,
  5,
  'Read Supreme Court judgments faster | LexRam Blog',
  'Five techniques for extracting the ratio from a Supreme Court judgment in under five minutes.',
  null,
  'LexRam Editorial',
  '2026-06-15T09:30:00+05:30',
  '2026-06-15T09:30:00+05:30',
  '2026-06-15T09:30:00+05:30'
),
(
  'seed-006',
  'hallucinated-citations-and-how-to-stop-them',
  'Hallucinated citations, and how to spot them in 30 seconds',
  'An LLM will swear a citation is real. Here is your 30-second verification protocol.',
  '/landing/justice.jpg',
  '<p>Indian courts have flagged hallucinated citations in filed affidavits. This is the protocol we run on every citation an AI produces — three checks, each under ten seconds — before it goes into a draft or a memo.</p>',
  'Opinion',
  array['AI Safety','Citations','Hallucination','Verification'],
  'published',
  null,
  4,
  'How to spot a hallucinated legal citation | LexRam Blog',
  'A 30-second protocol to verify that an AI-generated legal citation actually exists.',
  null,
  'LexRam Editorial',
  '2026-06-09T07:45:00+05:30',
  '2026-06-09T07:45:00+05:30',
  '2026-06-09T07:45:00+05:30'
)
on conflict (id) do nothing;

-- view_count exists per types/blog.ts; default to 0 for seed rows
update public.blog_posts set view_count = 0 where id like 'seed-%' and view_count is null;
